<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\VarDumper;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $username
 * @property string $name
 * @property string $surname
 * @property string $password
 * @property string $password_hash
 * @property string $access_token
 * @property string $auth_key
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Access[] $accesses
 * @property Note[] $notes
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{

    //public $password;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {

        return 'user';

    } // end function



    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'name'], 'required'],
            [['created_at', 'updated_at'], 'integer'],
            [['username', 'name', 'surname', 'password', 'password_hash', 'access_token', 'auth_key'], 'string', 'max' => 255],
        ];
    } // end function



    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'name' => 'Name',
            'surname' => 'Surname',
            'password' => 'Password',
            'password_hash' => 'Password Hash',
            'access_token' => 'Access Token',
            'auth_key' => 'Auth Key',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    } // end function



    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccesses()
    {

        return $this->hasMany(Access::className(), ['user_id' => 'id']);

    } // end function



    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNotes()
    {

        return $this->hasMany(Note::className(), ['creator_id' => 'id']);

    } // end function



    /**
     * @inheritdoc
     * @return UserQuery the active query used by this AR class.
     */
    public static function find()
    {

        return new UserQuery(get_called_class());

    } // end function


    /**
     * @return array
     */
    public function behaviors()
    {
        //return parent::behaviors(); // TODO: Change the autogenerated stub

        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false
            ]
        ];
    } // end function



    /**
     * Finds an identity by the given ID.
     *
     * @param string|int $id the ID to be looked for
     * @return IdentityInterface|null the identity object that matches the given ID.
     */
    public static function findIdentity($id)
    {

        return static::findOne($id);

    } // end function



    /**
     * Finds an identity by the given token.
     *
     * @param string $token the token to be looked for
     * @return IdentityInterface|null the identity object that matches the given token.
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {

        return static::findOne(['access_token' => $token]);

    } // end function



    /**
     * @return int|string current user ID
     */
    public function getId()
    {

        return $this->id;

    } // end function



    /**
     * @return string current user auth key
     */
    public function getAuthKey()
    {

        return $this->auth_key;

    } // end function



    /**
     * @param string $authKey
     * @return bool if auth key is valid for current user
     */
    public function validateAuthKey($authKey)
    {

        return $this->getAuthKey() === $authKey;

    } // end function


    /**
     * @param bool $insert
     * @return bool
     * @throws \yii\base\Exception
     */
    public function beforeSave($insert)
    {

        if (!parent::beforeSave($insert)) {
            return false;
        }

        if ($this->password) {
            $this->password_hash = Yii::$app->security->generatePasswordHash($this->password);
        }

        if ($this->isNewRecord) {
            $this->auth_key = Yii::$app->security->generateRandomString();
        }

        return true;

    } // end function


    /**
     * @param $password
     * @return bool
     * @throws \yii\base\Exception
     */
    public function validatePassword($password)
    {

        VarDumper::dump($password);

        $hash = Yii::$app->security->generatePasswordHash($password);

        if (Yii::$app->security->validatePassword($password, $hash)) {
            return true;
        } else {
            return false;
        }

    } // end function



    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    } // end function


} // end class
